package com.gerp.dartachalani.emas.ws.ds;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2021-09-13T14:32:57.580+05:45
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "http://ds.ws.emas/", name = "DSVerifyWS")
@XmlSeeAlso({ObjectFactory.class})
public interface DSVerifyWS {

    @WebMethod
    @RequestWrapper(localName = "verify", targetNamespace = "http://ds.ws.emas/", className = "com.gerp.dartachalani.emas.ws.ds.Verify")
    @ResponseWrapper(localName = "verifyResponse", targetNamespace = "http://ds.ws.emas/", className = "com.gerp.dartachalani.emas.ws.ds.VerifyResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String verify(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebMethod
    @RequestWrapper(localName = "verifyDetached", targetNamespace = "http://ds.ws.emas/", className = "com.gerp.dartachalani.emas.ws.ds.VerifyDetached")
    @ResponseWrapper(localName = "verifyDetachedResponse", targetNamespace = "http://ds.ws.emas/", className = "com.gerp.dartachalani.emas.ws.ds.VerifyDetachedResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String verifyDetached(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    );
}
