sentry:
  dsn: ${SENTRY_URL:http://418f351b29a14181919e4653f2b342c6@103.69.127.56:9000/1}
  exception-resolver-order: -2147483648
  max-breadcrumbs: 150
  logging:
    minimum-event-level: info
    minimum-breadcrumb-level: debug
  enable-tracing: true
  traces-sample-rate: 1.0
  attach-stacktrace: true
