rabbit:
  queue-1:
    name: email
    route: email-key
    exchange: email-exchange
  queue-2:
    name: notification
    route: notification-key
    exchange: notification-exchange
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: bitnami
